using System;
using System.Collections.Generic;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace WordSearch
{
    /// <summary>
    /// Interaction logic for GameWindowHelp.xaml
    /// </summary>
    public partial class GameWindowHelp : Window
    {
        public GameWindowHelp(string theme)
        {
            InitializeComponent();

            // Initialize theme 
            string themeUri = "";
            switch(theme){
                case "dark":
                    themeUri = "DarkTheme.xaml";
                    break;
                case "bright":
                    themeUri = "BrightTheme.xaml";
                    break;
                case "autumn":
                    themeUri = "AutumnTheme.xaml";
                    break;
            }

            ResourceDictionary skin = Application.LoadComponent(new Uri(themeUri, UriKind.Relative)) as ResourceDictionary;
            Resources.MergedDictionaries.Add(skin);

            // Populate text
            regenerateTitleLbl.Content = "RE-GENERATE LETTERS BUTTON";
            regenerateTextLbl.Content = "If you are not happy with your letters on the board, they can \nbe regenerated by " +
                "clicking on the Re-generate Letters button.";

            findTitleLbl.Content = "FIND WORD BUTTON";
            findTextLbl.Content = "Once you've inputed a word into the text box, clicking the Find Word \nbutton will display " +
                "the results. If your word exists on the board, it will be \nhighlighted, if it doesn't, no matches warning will appear.";

            matchedTitleLbl.Content = "MATCHED WORDS LIST";
            matchedTextLbl.Content = "This list will display all the words matched on the board. Should \nyou want to clear the " +
                "list or save it, please click on the menu button \nlocated on the upper strip.\n\nThere is an option availabe to " + 
                "also display matched words in reverse. To do so, \nclick on the Settings button located in the upper menu strip.";

            themeTitleLbl.Content = "CHANGE THEME";
            themeTextLbl.Content = "The theme (skin) of the board can be changed. To do so, click on the \nSettings button located on the " + 
                "upper strip and select an available option.";
        }
    }
}
